### ISSUE TITLE
pardump not reading READY HYSPLIT PARDUMP.#### files

### ISSUE THREAD

**Issue by klarsonSITC** [noaa-oar-arl/monetio#99] opened 2023-02-09 20:12 UTC
Hello, 
I'm attempting to use MONETIO to read the PARDUMP file generated by running HYSPLIT on the READY server. The "self.pardt" formatting in the MONETIO "pardump.open_dataset" function doesn't seem to be the same as the generated PARDUMP.#### (#### = job number) file. Here is what I'm doing:

Input: (minus path)
`import monetio as mio
import glob

folderpath = "path"
partfiles=glob.glob(folderpath+"*/PARDUMP*")
part = mio.pardump.open_dataset(partfiles[0],century=2000,verbose=1)`

Output:
`Record Header  [(28, 10020, 1, 22, 12, 24, 23, 0)]
Date  2022-12-24 23:00:00  ****  None
Adding data  [(28, 10020, 1, 22, 12, 24, 23, 0)] 2022-12-24 23:00:00
Record Header  [(7, 0, 1, 1, 8907, 20, 4, 940279797)]
Traceback (most recent call last):

  File "\\sitc2\Planning\USER\WATER\6_AIR_QUALITY\C_AQ_BKGD_RESEARCH\4_PROGRAMS\Python\Plot_Hysplit.py", line 21, in <module>
    part = mio.pardump.open_dataset(partfiles[0],century=2000,verbose=1)

  File "C:\Users\klarson\Anaconda3\lib\site-packages\monetio\models\pardump.py", line 36, in open_dataset
    pardf = pdump.read(drange=drange, century=century, verbose=verbose)

  File "C:\Users\klarson\Anaconda3\lib\site-packages\monetio\models\pardump.py", line 191, in read
    pdate = datetime.datetime(

ValueError: month must be in 1..12`

Using the Debugger, I looked at the par_frame before the padding is dropped. There seems to be an offset as the pandas array fills "lon", "ht", and "su" with the latitude, longitude, and height values (see attached screen shot). I'm not sure if this is a general issue with all PARDUMP HYSPLIT files or if this is solely a PARDUMP generated-on-the-READY-server HYSPLIT file issue.  I have the same dispersion back trajectory from READY file I was attempting to read attached as a zip file below. 

<img width="804" alt="par_frame" src="https://user-images.githubusercontent.com/124926390/217923091-37aca98e-f7a1-4328-b551-5ef7ca440ad8.PNG">

[2022122500.zip](https://github.com/noaa-oar-arl/monetio/files/10700980/2022122500.zip)

**Comment by zmoon** [comment] 2023-02-09 20:46
Hi @klarsonSITC , thanks for this report. I know @amcz made some changes to HYSPLIT reading that we haven't released yet, but I don't think the pardump reader was touched.

**Comment by amcz** [comment] 2023-02-14 16:50
I cannot reproduce your error using the PARDUMP.21498 file you provided. See screenshot.
Can you provide more information on your system?

![AMC_PARDUMP_TEST](https://user-images.githubusercontent.com/19688734/218777716-c9945589-ff29-427b-8226-a862154e62da.png)

**Comment by klarsonSITC** [comment] 2023-02-15 17:54
<img width="232" alt="20230215_system" src="https://user-images.githubusercontent.com/124926390/219112594-def5435f-2d13-45db-9c95-9ac7671644a8.PNG">
Sorry for the delay, I have a windows system. Thank you for the help!

**Comment by zmoon** [comment] 2023-02-24 16:16
@klarsonSITC this should now be fixed in our `develop` branch. And I will try to do a new conda-forge release soon.

**Comment by bbakernoaa** [comment] 2023-04-06 20:23
@klarsonSITC Has this been resolved?

**Closed as completed** 2023-04-20 22:02 UTC
Labels: bug
