### ISSUE TITLE
Create TEMPO L2 reader

### ISSUE THREAD

**Issue by dwfncar** [noaa-oar-arl/monetio#176] opened 2024-06-06 19:16 UTC
Create sat/_tempo_l2_mm.py TEMPO reader.

**Comment by zmoon** [comment] 2024-09-05 16:09
Would #188 close this?

**Comment by blychs** [comment] 2024-09-19 20:24
I think it does. IMHO, this can be closed.
EDIT: Only the NO2 reader is done. HCHO should be very straightforward, and soon we should be able to get it done.

**Comment by zmoon** [comment] 2024-09-19 21:08
I'll plan to close this one though, since it's essentially a duplicate of #150

**Closed as completed** 2024-10-09 02:18 UTC
Labels: enhancement, in-develop
